Repository FESOM/fesom2, pull requests merged in 2024-08, with the labels that each got.

#616 Bugfix: Reintroduce the calculation of auxiliary latitude variables for transient tracer…
  src/oce_ale_tracer.F90
Labels: bug

#497 Draft: Refactoring addsshsubcycl
  config/namelist.dyn
  src/MOD_DYN.F90
  src/associate_mesh_ass.h
  src/gen_modules_diag.F90
  src/io_blowup.F90
  src/io_meandata.F90
  src/oce_ale.F90
  src/oce_ale_ssh_splitexpl_subcycl.F90
  src/oce_ale_tracer.F90
  src/oce_ale_vel_rhs.F90
  src/oce_dyn.F90
  src/oce_setup_step.F90
  src/write_step_info.F90
  work/job_albedo_chain
Labels: help wanted, wait until approved

#578 Add Discret Variance Decay (DVD) diagnostic of Knut and Sergey
  config/namelist.config
  config/namelist.cvmix
  src/MOD_TRACER.F90
  src/gen_modules_diag.F90
  src/io_meandata.F90
  src/oce_adv_tra_driver.F90
  src/oce_ale.F90
  src/oce_ale_pressure_bv.F90
  src/oce_ale_tracer.F90
  src/oce_setup_step.F90
  src/oce_tracer_mod.F90
  src/toy_channel_soufflet.F90
  src/write_step_info.F90
  work/job_albedo_chain
Labels: changes testcase

#612 Main ifs thermo
  setups/test_pi/setup.yml
  src/MOD_ICE.F90
  src/ice_setup_step.F90
  src/ice_thermo_cpl.F90
  src/io_meandata.F90
Labels: changes testcase

#120 Workbench fixsrfstress
  setups/test_pi/setup.yml
  src/gen_modules_cvmix_kpp.F90
  src/gen_modules_cvmix_tke.F90
  src/ice_oce_coupling.F90
  src/ice_setup_step.F90
  src/oce_ale_mixing_kpp.F90
  src/oce_mo_conv.F90
Labels: changes testcase
