Repository FESOM/fesom2, pull requests merged in 2024-06, with the labels that each got.

#571 Production de merge into refactoring
  .github/inactive_workflows/fesom2_icepack.yml
  .github/workflows/fesom2.1.yml
  .github/workflows/fesom2_openmp.yml
  CMakeLists.txt
  cmake/FindBLAS.cmake
  cmake/fesom_export.cmake
  cmake/fesom_setup.cmake
  config/namelist.forcing
  configure.sh
  env.sh
  env/levante.dkrz.de/shell.nvhpc
  env/ubuntu/shell
  lib/parms/CMakeLists.txt
  src/CMakeLists.txt
  src/GitRepositoryInfo.cmake
  src/MOD_DYN.F90
  src/MOD_ICE.F90
  src/MOD_MESH.F90
  src/MOD_PARTIT.F90
  src/MOD_TRACER.F90
  src/async_threads_cpp/CMakeLists.txt
  src/async_threads_module.F90
  src/fesom-config.cmake.in
  src/fesom_module.F90
  src/gen_forcing_init.F90
  src/gen_halo_exchange.F90
  src/gen_modules_config.F90
  src/gen_modules_diag.F90
  src/gen_modules_forcing.F90
  src/gen_modules_partitioning.F90
  src/gen_modules_read_NetCDF.F90
  src/gen_surface_forcing.F90
  src/icb_step.F90
  src/ice_EVP.F90
  src/ice_fct.F90
  src/ice_oce_coupling.F90
  src/ice_setup_step.F90
  src/ice_thermo_cpl.F90
  src/ifs_interface/ifs_interface.F90
  src/ifs_interface/ifs_modules.F90
  src/ifs_interface/iom.F90
  src/ifs_interface/mpp_io.F90
  src/io_meandata.F90
  src/io_netcdf_file_module.F90
  src/io_netcdf_module.F90
  src/oce_adv_tra_driver.F90
  src/oce_adv_tra_fct.F90
  src/oce_adv_tra_hor.F90
  src/oce_adv_tra_ver.F90
  src/oce_ale_tracer.F90
  src/oce_tracer_mod.F90
  test_downstream/.gitignore
  test_downstream/CMakeLists.txt
  test_downstream/README
  test_downstream/main.F90
  work/job_lumi
Labels: production_DE

#354 Refactoring better metadata
  .github/workflows/fesom2.1.yml
  .gitignore
  docs/code_documentation/io_mesh_info.rst
  docs/conf.py
  docs/index.rst
  src/io_meandata.F90
  src/io_mesh_info.F90
  test.sh
  test_pgierz/actual_ugrid_ncdump.txt
  test_pgierz/example_ugrid_ncdump.txt
  test_pgierz/test_one_timestep.sh
Labels: leave it for the end

#603 fix landice fw bug
  src/ice_oce_coupling.F90
Labels: bug
